//! Textual LLVM IR from the typed program.
//!
//! Locals live in `alloca` slots (clang's mem2reg turns them into registers).
//! Integer arithmetic is checked with the `*.with.overflow` intrinsics and
//! traps with a source location. Runtime functions take only scalars and
//! pointers, so no C struct-passing ABI is involved.
//!
//! `str` is `{ ptr buf, i64 off, i64 len }`, where `buf` points to a buffer
//! with a 16-byte header (reference count, capacity) followed by the bytes.
//! Literals are static buffers with a count of 0, which is never freed.

use crate::ast::{AssignOp, BinOp};
use crate::check::{Builtin, Func, Program, TBlock, TExpr, TStmt, Ty, TK};
use crate::source::{Source, Span};
use std::fmt::Write;

pub fn emit(p: &Program, src: &Source) -> String {
    let mut g = Gen { src, strs: Vec::new(), cstrs: Vec::new(), f: FnState::default() };
    let file_const = g.cstr(src.path.as_bytes());
    let mut body = String::new();
    for f in &p.funcs {
        body.push_str(&g.func(p, f, &file_const));
        body.push('\n');
    }
    let mut out = String::new();
    out.push_str("; generated by ovt\n\n%str = type { ptr, i64, i64 }\n\n");
    for (i, s) in g.strs.iter().enumerate() {
        let _ = writeln!(
            out,
            "@.str.{i} = private unnamed_addr constant {{ i64, i64, [{n} x i8] }} {{ i64 0, i64 {n}, [{n} x i8] c\"{}\" }}, align 8",
            escape(s),
            n = s.len()
        );
    }
    for (i, s) in g.cstrs.iter().enumerate() {
        let _ = writeln!(out, "@.cstr.{i} = private unnamed_addr constant [{} x i8] c\"{}\\00\"", s.len() + 1, escape(s));
    }
    out.push_str(
        "
declare void @ovt_rt_init(i32, ptr)
declare void @ovt_rt_exit()
declare void @ovt_print_str(ptr, i64, i64)
declare void @ovt_print_int(i64)
declare void @ovt_print_bool(i32)
declare void @ovt_trap(ptr, i64, ptr, i32, i32) noreturn cold
declare { i64, i1 } @llvm.sadd.with.overflow.i64(i64, i64)
declare { i64, i1 } @llvm.ssub.with.overflow.i64(i64, i64)
declare { i64, i1 } @llvm.smul.with.overflow.i64(i64, i64)

",
    );
    out.push_str(&body);
    let _ = writeln!(
        out,
        "define i32 @main(i32 %argc, ptr %argv) {{\n  call void @ovt_rt_init(i32 %argc, ptr %argv)\n  call void @\"{}\"()\n  call void @ovt_rt_exit()\n  ret i32 0\n}}",
        p.funcs[p.main].mangled
    );
    out
}

fn escape(bytes: &[u8]) -> String {
    let mut s = String::new();
    for &b in bytes {
        if (0x20..0x7f).contains(&b) && b != b'"' && b != b'\\' {
            s.push(b as char);
        } else {
            let _ = write!(s, "\\{b:02X}");
        }
    }
    s
}

fn llty(t: &Ty) -> &'static str {
    match t {
        Ty::Int => "i64",
        Ty::Bool => "i1",
        Ty::Str => "%str",
        Ty::Unit | Ty::Never | Ty::Error => "void",
    }
}

#[derive(Default)]
struct FnState {
    allocas: String,
    code: String,
    tmp: usize,
    label: usize,
    terminated: bool,
    cur_label: String,
    slots: Vec<String>,
    /// (continue target, break target) for each enclosing loop.
    loops: Vec<(String, String)>,
    ret: Option<Ty>,
    file: String,
}

struct Gen<'a> {
    src: &'a Source,
    strs: Vec<Vec<u8>>,
    cstrs: Vec<Vec<u8>>,
    f: FnState,
}

/// An LLVM value: its type and how to write it as an operand.
struct Val {
    ty: &'static str,
    repr: String,
}

impl<'a> Gen<'a> {
    fn cstr(&mut self, bytes: &[u8]) -> String {
        let i = self.cstrs.len();
        self.cstrs.push(bytes.to_vec());
        format!("@.cstr.{i}")
    }

    fn str_const(&mut self, bytes: &[u8]) -> String {
        let i = self.strs.len();
        self.strs.push(bytes.to_vec());
        format!("{{ ptr @.str.{i}, i64 0, i64 {} }}", bytes.len())
    }

    fn tmp(&mut self) -> String {
        self.f.tmp += 1;
        format!("%t{}", self.f.tmp)
    }

    fn new_label(&mut self, hint: &str) -> String {
        self.f.label += 1;
        format!("{hint}.{}", self.f.label)
    }

    /// Emits an instruction, opening an unreachable block first if the
    /// current one already ended.
    fn inst(&mut self, s: &str) {
        if self.f.terminated {
            let l = self.new_label("dead");
            self.f.code.push_str(&format!("{l}:\n"));
            self.f.cur_label = l;
            self.f.terminated = false;
        }
        self.f.code.push_str("  ");
        self.f.code.push_str(s);
        self.f.code.push('\n');
    }

    fn term(&mut self, s: &str) {
        self.inst(s);
        self.f.terminated = true;
    }

    fn start_label(&mut self, l: &str) {
        if !self.f.terminated {
            self.f.code.push_str(&format!("  br label %{l}\n"));
        }
        self.f.code.push_str(&format!("{l}:\n"));
        self.f.cur_label = l.to_string();
        self.f.terminated = false;
    }

    fn func(&mut self, p: &Program, f: &Func, file: &str) -> String {
        self.f = FnState { file: file.to_string(), ret: Some(f.ret.clone()), cur_label: "entry".into(), ..Default::default() };
        for (i, l) in f.locals.iter().enumerate() {
            let slot = format!("%l{i}");
            let _ = writeln!(self.f.allocas, "  {slot} = alloca {}", llty(&l.ty));
            self.f.slots.push(slot);
        }
        let mut params = Vec::new();
        for (i, &id) in f.params.iter().enumerate() {
            let t = llty(&f.locals[id].ty);
            params.push(format!("{t} %p{i}"));
            let slot = self.f.slots[id].clone();
            self.inst(&format!("store {t} %p{i}, ptr {slot}"));
        }
        for (cond, text) in &f.pre {
            let c = self.expr(p, cond);
            let msg = format!("precondition failed: {text}");
            self.trap_unless(&c.repr, &msg, cond.span);
        }
        self.block(p, &f.body);
        if !self.f.terminated {
            if f.ret == Ty::Unit {
                self.term("ret void");
            } else {
                self.term("unreachable");
            }
        }
        format!(
            "define internal {} @\"{}\"({}) {{\nentry:\n{}{}}}\n",
            llty(&f.ret),
            f.mangled,
            params.join(", "),
            self.f.allocas,
            self.f.code
        )
    }

    fn block(&mut self, p: &Program, b: &TBlock) -> Option<Val> {
        for s in &b.stmts {
            self.stmt(p, s);
        }
        b.value.as_ref().map(|v| self.expr(p, v))
    }

    fn stmt(&mut self, p: &Program, s: &TStmt) {
        match s {
            TStmt::Let(id, v) | TStmt::Assign(id, AssignOp::Set, v, _) => {
                let val = self.expr(p, v);
                if v.ty != Ty::Never {
                    let slot = self.f.slots[*id].clone();
                    self.inst(&format!("store {} {}, ptr {slot}", val.ty, val.repr));
                }
            }
            TStmt::Assign(id, op, v, span) => {
                let slot = self.f.slots[*id].clone();
                let cur = self.tmp();
                self.inst(&format!("{cur} = load i64, ptr {slot}"));
                let rhs = self.expr(p, v);
                let bop = match op {
                    AssignOp::Add => BinOp::Add,
                    AssignOp::Sub => BinOp::Sub,
                    AssignOp::Mul => BinOp::Mul,
                    AssignOp::Div => BinOp::Div,
                    AssignOp::Rem => BinOp::Rem,
                    AssignOp::Set => unreachable!(),
                };
                let r = self.int_op(bop, &cur, &rhs.repr, *span);
                self.inst(&format!("store i64 {r}, ptr {slot}"));
            }
            TStmt::Expr(e) => {
                self.expr(p, e);
            }
            TStmt::While(cond, body) => {
                let head = self.new_label("while");
                let bl = self.new_label("body");
                let end = self.new_label("end");
                self.start_label(&head);
                let c = self.expr(p, cond);
                self.term(&format!("br i1 {}, label %{bl}, label %{end}", c.repr));
                self.start_label(&bl);
                self.f.loops.push((head.clone(), end.clone()));
                self.block(p, body);
                self.f.loops.pop();
                self.term(&format!("br label %{head}"));
                self.start_label(&end);
            }
            TStmt::ForRange { var, lo, hi, inclusive, body } => {
                let lo = self.expr(p, lo);
                let hi = self.expr(p, hi);
                let slot = self.f.slots[*var].clone();
                self.inst(&format!("store i64 {}, ptr {slot}", lo.repr));
                let head = self.new_label("for");
                let bl = self.new_label("body");
                let step = self.new_label("step");
                let end = self.new_label("end");
                self.start_label(&head);
                let i = self.tmp();
                self.inst(&format!("{i} = load i64, ptr {slot}"));
                let c = self.tmp();
                let cmp = if *inclusive { "sle" } else { "slt" };
                self.inst(&format!("{c} = icmp {cmp} i64 {i}, {}", hi.repr));
                self.term(&format!("br i1 {c}, label %{bl}, label %{end}"));
                self.start_label(&bl);
                self.f.loops.push((step.clone(), end.clone()));
                self.block(p, body);
                self.f.loops.pop();
                self.start_label(&step);
                let i2 = self.tmp();
                self.inst(&format!("{i2} = load i64, ptr {slot}"));
                if *inclusive {
                    // Stop at the last value, so `..=` up to the largest int doesn't overflow.
                    let last = self.tmp();
                    let next_l = self.new_label("next");
                    self.inst(&format!("{last} = icmp eq i64 {i2}, {}", hi.repr));
                    self.term(&format!("br i1 {last}, label %{end}, label %{next_l}"));
                    self.start_label(&next_l);
                }
                let n = self.tmp();
                self.inst(&format!("{n} = add i64 {i2}, 1"));
                self.inst(&format!("store i64 {n}, ptr {slot}"));
                self.term(&format!("br label %{head}"));
                self.start_label(&end);
            }
        }
    }

    fn loc(&self, span: Span) -> (u32, u32) {
        self.src.line_col(span.lo)
    }

    fn trap_call(&mut self, msg_ptr: &str, msg_len: &str, span: Span) {
        let (line, col) = self.loc(span);
        let file = self.f.file.clone();
        self.inst(&format!("call void @ovt_trap(ptr {msg_ptr}, i64 {msg_len}, ptr {file}, i32 {line}, i32 {col})"));
        self.term("unreachable");
    }

    fn trap_msg(&mut self, msg: &str, span: Span) {
        let c = self.cstr(msg.as_bytes());
        self.trap_call(&c, &msg.len().to_string(), span);
    }

    /// Traps with `msg` unless `ok` (an `i1`) is true.
    fn trap_unless(&mut self, ok: &str, msg: &str, span: Span) {
        let good = self.new_label("ok");
        let bad = self.new_label("trap");
        self.term(&format!("br i1 {ok}, label %{good}, label %{bad}"));
        self.start_label(&bad);
        self.trap_msg(msg, span);
        self.start_label(&good);
    }

    fn trap_if(&mut self, bad_cond: &str, msg: &str, span: Span) {
        let ok = self.tmp();
        self.inst(&format!("{ok} = xor i1 {bad_cond}, true"));
        self.trap_unless(&ok, msg, span);
    }

    fn int_op(&mut self, op: BinOp, a: &str, b: &str, span: Span) -> String {
        let r = self.tmp();
        match op {
            BinOp::Add | BinOp::Sub | BinOp::Mul => {
                let name = match op {
                    BinOp::Add => "sadd",
                    BinOp::Sub => "ssub",
                    _ => "smul",
                };
                let pair = self.tmp();
                self.inst(&format!("{pair} = call {{ i64, i1 }} @llvm.{name}.with.overflow.i64(i64 {a}, i64 {b})"));
                self.inst(&format!("{r} = extractvalue {{ i64, i1 }} {pair}, 0"));
                let o = self.tmp();
                self.inst(&format!("{o} = extractvalue {{ i64, i1 }} {pair}, 1"));
                let what = match op {
                    BinOp::Add => "addition",
                    BinOp::Sub => "subtraction",
                    _ => "multiplication",
                };
                self.trap_if(&o, &format!("integer overflow in {what}; use `{}%` to wrap", op.text()), span);
            }
            BinOp::Div | BinOp::Rem => {
                let z = self.tmp();
                self.inst(&format!("{z} = icmp eq i64 {b}, 0"));
                self.trap_if(&z, if op == BinOp::Div { "division by zero" } else { "remainder by zero" }, span);
                let m1 = self.tmp();
                let mn = self.tmp();
                let both = self.tmp();
                self.inst(&format!("{m1} = icmp eq i64 {b}, -1"));
                self.inst(&format!("{mn} = icmp eq i64 {a}, -9223372036854775808"));
                self.inst(&format!("{both} = and i1 {m1}, {mn}"));
                self.trap_if(&both, "integer overflow in division", span);
                let ins = if op == BinOp::Div { "sdiv" } else { "srem" };
                self.inst(&format!("{r} = {ins} i64 {a}, {b}"));
            }
            BinOp::AddW | BinOp::SubW | BinOp::MulW => {
                let ins = match op {
                    BinOp::AddW => "add",
                    BinOp::SubW => "sub",
                    _ => "mul",
                };
                self.inst(&format!("{r} = {ins} i64 {a}, {b}"));
            }
            BinOp::Shl | BinOp::Shr => {
                let big = self.tmp();
                self.inst(&format!("{big} = icmp ugt i64 {b}, 63"));
                self.trap_if(&big, "shift amount must be between 0 and 63", span);
                let ins = if op == BinOp::Shl { "shl" } else { "ashr" };
                self.inst(&format!("{r} = {ins} i64 {a}, {b}"));
            }
            BinOp::BitAnd | BinOp::BitOr | BinOp::BitXor => {
                let ins = match op {
                    BinOp::BitAnd => "and",
                    BinOp::BitOr => "or",
                    _ => "xor",
                };
                self.inst(&format!("{r} = {ins} i64 {a}, {b}"));
            }
            _ => unreachable!("not an integer operator"),
        }
        r
    }

    fn expr(&mut self, p: &Program, e: &TExpr) -> Val {
        let ty = llty(&e.ty);
        match &e.kind {
            TK::Int(v) => Val { ty: "i64", repr: v.to_string() },
            TK::Bool(b) => Val { ty: "i1", repr: if *b { "true" } else { "false" }.into() },
            TK::Str(bytes) => Val { ty: "%str", repr: self.str_const(bytes) },
            TK::Local(id) => {
                let t = self.tmp();
                let slot = self.f.slots[*id].clone();
                self.inst(&format!("{t} = load {ty}, ptr {slot}"));
                Val { ty, repr: t }
            }
            TK::Call(index, args) => {
                let mut ops = Vec::new();
                for a in args {
                    let v = self.expr(p, a);
                    ops.push(format!("{} {}", v.ty, v.repr));
                }
                let callee = &p.funcs[*index];
                let rty = llty(&callee.ret);
                if rty == "void" {
                    self.inst(&format!("call void @\"{}\"({})", callee.mangled, ops.join(", ")));
                    Val { ty: "void", repr: String::new() }
                } else {
                    let t = self.tmp();
                    self.inst(&format!("{t} = call {rty} @\"{}\"({})", callee.mangled, ops.join(", ")));
                    Val { ty: rty, repr: t }
                }
            }
            TK::Builtin(b, args, text) => self.builtin(p, *b, args, text, e.span),
            TK::Bin(op, l, r) => self.binary(p, *op, l, r, e.span),
            TK::Neg(inner) => {
                let v = self.expr(p, inner);
                let r = self.int_op(BinOp::Sub, "0", &v.repr, e.span);
                Val { ty: "i64", repr: r }
            }
            TK::Not(inner) => {
                let v = self.expr(p, inner);
                let t = self.tmp();
                self.inst(&format!("{t} = xor i1 {}, true", v.repr));
                Val { ty: "i1", repr: t }
            }
            TK::If(cond, then, els) => {
                let c = self.expr(p, cond);
                let tl = self.new_label("then");
                let el = self.new_label("else");
                let end = self.new_label("endif");
                let slot = if ty != "void" {
                    let s = format!("%if{}", self.f.label);
                    let _ = writeln!(self.f.allocas, "  {s} = alloca {ty}");
                    Some(s)
                } else {
                    None
                };
                self.term(&format!("br i1 {}, label %{tl}, label %{}", c.repr, if els.is_some() { &el } else { &end }));
                self.start_label(&tl);
                let tv = self.block(p, then);
                if let (Some(s), Some(v)) = (&slot, tv) {
                    if !self.f.terminated && v.ty != "void" {
                        self.inst(&format!("store {ty} {}, ptr {s}", v.repr));
                    }
                }
                if !self.f.terminated {
                    self.term(&format!("br label %{end}"));
                }
                if let Some(els) = els {
                    self.start_label(&el);
                    let ev = self.block(p, els);
                    if let (Some(s), Some(v)) = (&slot, ev) {
                        if !self.f.terminated && v.ty != "void" {
                            self.inst(&format!("store {ty} {}, ptr {s}", v.repr));
                        }
                    }
                    if !self.f.terminated {
                        self.term(&format!("br label %{end}"));
                    }
                }
                self.start_label(&end);
                if e.ty == Ty::Never {
                    self.term("unreachable");
                }
                match slot {
                    Some(s) if e.ty != Ty::Never => {
                        let t = self.tmp();
                        self.inst(&format!("{t} = load {ty}, ptr {s}"));
                        Val { ty, repr: t }
                    }
                    _ => Val { ty: "void", repr: String::new() },
                }
            }
            TK::Return(v) => {
                match v {
                    Some(v) if v.ty != Ty::Never => {
                        let val = self.expr(p, v);
                        self.term(&format!("ret {} {}", val.ty, val.repr));
                    }
                    Some(v) => {
                        self.expr(p, v);
                    }
                    None => {
                        if self.f.ret == Some(Ty::Unit) {
                            self.term("ret void");
                        }
                    }
                }
                Val { ty: "void", repr: String::new() }
            }
            TK::Break | TK::Continue => {
                let (cont, brk) = self.f.loops.last().cloned().expect("checked: inside a loop");
                let target = if matches!(e.kind, TK::Break) { brk } else { cont };
                self.term(&format!("br label %{target}"));
                Val { ty: "void", repr: String::new() }
            }
        }
    }

    fn binary(&mut self, p: &Program, op: BinOp, l: &TExpr, r: &TExpr, span: Span) -> Val {
        if matches!(op, BinOp::And | BinOp::Or) {
            let a = self.expr(p, l);
            let from = self.f.cur_label.clone();
            let rhs = self.new_label("rhs");
            let end = self.new_label("logic");
            if op == BinOp::And {
                self.term(&format!("br i1 {}, label %{rhs}, label %{end}", a.repr));
            } else {
                self.term(&format!("br i1 {}, label %{end}, label %{rhs}", a.repr));
            }
            self.start_label(&rhs);
            let b = self.expr(p, r);
            let rhs_end = self.f.cur_label.clone();
            self.start_label(&end);
            let t = self.tmp();
            let short = if op == BinOp::And { "false" } else { "true" };
            self.inst(&format!("{t} = phi i1 [ {short}, %{from} ], [ {}, %{rhs_end} ]", b.repr));
            return Val { ty: "i1", repr: t };
        }
        let a = self.expr(p, l);
        let b = self.expr(p, r);
        if op.is_comparison() {
            let t = self.tmp();
            let cc = match op {
                BinOp::Eq => "eq",
                BinOp::Ne => "ne",
                BinOp::Lt => "slt",
                BinOp::Le => "sle",
                BinOp::Gt => "sgt",
                _ => "sge",
            };
            self.inst(&format!("{t} = icmp {cc} {} {}, {}", a.ty, a.repr, b.repr));
            return Val { ty: "i1", repr: t };
        }
        let r = self.int_op(op, &a.repr, &b.repr, span);
        Val { ty: "i64", repr: r }
    }

    fn builtin(&mut self, p: &Program, b: Builtin, args: &[TExpr], text: &str, span: Span) -> Val {
        let void = Val { ty: "void", repr: String::new() };
        match b {
            Builtin::Print => {
                let v = self.expr(p, &args[0]);
                match args[0].ty {
                    Ty::Str => {
                        let (buf, off, len) = self.str_parts(&v.repr);
                        self.inst(&format!("call void @ovt_print_str(ptr {buf}, i64 {off}, i64 {len})"));
                    }
                    Ty::Int => self.inst(&format!("call void @ovt_print_int(i64 {})", v.repr)),
                    Ty::Bool => {
                        let z = self.tmp();
                        self.inst(&format!("{z} = zext i1 {} to i32", v.repr));
                        self.inst(&format!("call void @ovt_print_bool(i32 {z})"));
                    }
                    Ty::Unit | Ty::Never | Ty::Error => {}
                }
                void
            }
            Builtin::Trap => {
                let v = self.expr(p, &args[0]);
                let (ptr, len) = self.str_data(&v.repr);
                self.trap_call(&ptr, &len, span);
                void
            }
            Builtin::Todo => {
                self.trap_msg("reached `todo()`", span);
                void
            }
            Builtin::Assert => {
                let c = self.expr(p, &args[0]);
                let good = self.new_label("ok");
                let bad = self.new_label("assert");
                self.term(&format!("br i1 {}, label %{good}, label %{bad}", c.repr));
                self.start_label(&bad);
                if let Some(msg) = args.get(1) {
                    let v = self.expr(p, msg);
                    let (ptr, len) = self.str_data(&v.repr);
                    self.trap_call(&ptr, &len, span);
                } else {
                    self.trap_msg(&format!("assertion failed: {text}"), span);
                }
                self.start_label(&good);
                void
            }
        }
    }

    fn str_parts(&mut self, v: &str) -> (String, String, String) {
        let buf = self.tmp();
        let off = self.tmp();
        let len = self.tmp();
        self.inst(&format!("{buf} = extractvalue %str {v}, 0"));
        self.inst(&format!("{off} = extractvalue %str {v}, 1"));
        self.inst(&format!("{len} = extractvalue %str {v}, 2"));
        (buf, off, len)
    }

    /// A pointer to a string's bytes, and its length.
    fn str_data(&mut self, v: &str) -> (String, String) {
        let (buf, off, len) = self.str_parts(v);
        let at = self.tmp();
        let ptr = self.tmp();
        self.inst(&format!("{at} = add i64 {off}, 16"));
        self.inst(&format!("{ptr} = getelementptr i8, ptr {buf}, i64 {at}"));
        (ptr, len)
    }
}
